modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/Plutosion/Leashed/issues"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId="leashed"
version="${file.jarVersion}"
displayName="Leashed"

displayURL="http://twitter.com/Plutosion"
credits=""
authors="Plutosion"
description='''
Get leashed!
'''
[[dependencies.leashed]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"