modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
#issueTrackerURL="http://my.issue.tracker/"
license="GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId="leashed"
version="${file.jarVersion}"
displayName="Leashed"

displayURL="http://twitter.com/Plutosion"
credits=""
authors="Plutosion"
description='''
Get leashed!
'''