modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Plutosion/Leashed/issues"
license="GNU GPL V3"

[[mods]]
modId="leashed"
version="${file.jarVersion}"
displayName="Leashed"

displayURL="http://twitter.com/Plutosion"
credits=""
authors="Plutosion"
description='''
Get leashed!
'''
[[dependencies.leashed]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.leashed]]
modId="forge"
mandatory=true
versionRange="[38.0.6,)"
ordering="NONE"
side="BOTH"